### ISSUE TITLE
Python mode install stalls at 100%

### ISSUE THREAD

**Issue by mbuccoli** [jdf/processing.py#123]
When I try to install the python mode, the progress bar for downloading is filled, but the "Downloading" label is still there and stacked at 100%, but the installation does not succeed.

I had no problem installing other modes.

I just tried to remove and install again Processing 2.2.1 (I'm from a Mac) but nothing changed.

![screen shot 2014-12-01 at 15 59 27](https://cloud.githubusercontent.com/assets/7048795/5247493/1ae9dda0-7973-11e4-9fdc-d9a1c3807137.png)

**Comment by jo3w4rd** [comment]
I've run into this issue, too. Mac 10.95, Processing 2.2.1 (latest build available). I am able to install other Modes (JavaScript and CoffeeScript).
