### ISSUE TITLE
json.loads() takes forever to load JSON with 46k entries.

### ISSUE THREAD

**Issue by Spaxe** [jdf/processing.py#126]
Minimal code example (change filepath as necessary):

    import json
    
    with open('data.json') as f:
        return json.loads(f.read())

This works with files at 170KB - 350KB, but I have a file that is at 9MB, and it stalls. I can still stop the program (it's not freezing), but it isn't very fast.

Small file: https://github.com/Spaxe/roguelike-universe/blob/master/generated/roguelike-relational-maps.json
Large file: https://github.com/Spaxe/roguelike-universe/blob/master/generated/games.json

In normal CPython it would load under 1 second.

Is this a issue you can look into, or should I bug the Jython guys?

Update: tried with a smaller file (2MB), still no avail. Maybe it's the number of entries?
https://github.com/Spaxe/roguelike-universe/blob/master/generated/games-years.json

**Comment by jdf** [comment]
Looks to be related to http://bugs.jython.org/issue2167. It's not trivial for me to update to a more recent Jython build, because I use a patched Jython. I'll see what i can do in the coming days.

**Comment by jdf** [comment]
Fixed in version @0405.
![selfie-1](http://i.imgur.com/Yf3TE7I.png)

**Comment by Spaxe** [comment]
All good, I'm cutting down my input lots before using Processing Python mode to work around this issue.
