### ISSUE TITLE
Android mode

### ISSUE THREAD

**Issue by eviltnan** [jdf/processing.py#127]
Hey guys,

good job, I'm speechless... Nevertheless: is there a possibility to use both Python and Android mode simultaneously? Or somehow export Python-written code as android app, like Android mode does?

Thank you in advance.

Regards,
Sergey

**Comment by sinistersnare** [comment]
Jython, which is how Python works in the Java runtime, currently does not support android.

The general idea is that Jython interprets python code, but with the (in development) tool [clamp](https://github.com/jythontools/clamp), it seems that Jython code could be translated directly to Java bytecode. At that point, it seems that dex will be able to convert the bytecode to dalvik bytecode.

This may be a tad outdated, I worked with Jython a year ago for a small project I was working on at the time, and that was the situation then. 

(I know this didnt really help, just felt like offering some insight)

**Comment by eviltnan** [comment]
Hey Davis,

Thank you for your answer! I just supposed this could be ported under jni
in the same way as kivy framework does.

Cheers
Sergey

чт, 19 марта 2015, 7:04, Davis Silverman <notifications@github.com>:

**Comment by sinistersnare** [comment]
Jython is made in Java, not C, so JNI probably cant be used.
