### ISSUE TITLE
Issue trying to import wave

### ISSUE THREAD

**Issue by KelsonBall** [jdf/processing.py#138]
I've put wave.py in my sketch folder, and then it said it couldn't import audioop, so I found audioop.py (online, I couldn't find it in my Pytho34\Lib) and put it in the sketch folder as well. Now when I run

import wave

and I get the following error:

processing.app.SketchException: Maybe there's an unclosed paren or quote mark somewhere before this line?
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(Unknown Source)
	at jycessing.mode.run.SketchRunner.access$300(Unknown Source)
	at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I am on Windows 7 with Python 3.4 and Processing 2.2.1.

**Comment by jdf** [comment]
processing.py does not use whatever Python you have installed; it uses its own private copy of a Jython distribution that is almost, but not quite, Python 2.7.
