### ISSUE TITLE
Building processing.py from source

### ISSUE THREAD

**Issue by SudShekhar** [jdf/processing.py#141]
Hi,

I am trying to build processing.py from source and have followed the instructions given in HOWTO-HACK.txt but when I run the `ant test` command in cloned repository, I keep on getting the following error:

    Buildfile: /home/shekhar/Documents/gsoc/processing.py/build.xml

    check-processing-needs-build:

    build-processing:
       [echo] Building processing.

    BUILD FAILED
    /home/shekhar/Documents/processing.py/build.xml:204: Basedir /home/shekhar/Documents/processing/build does not exist

I tried searching for ways to rectify this but couldn't. Can someone help me resolve this? I am using Ubuntu 14.04.

**Comment by tildebyte** [comment]
I would think that executing

````bash
touch /home/shekhar/Documents/processing/build
````

would fix it, **assuming that** you have cloned the Processing git repo into `/home/shekhar/Documents/processing`

Note that the Processing.py build file explicitly looks for the *Processing* source tree in `../processing`.

**Comment by SudShekhar** [comment]
I tried by creating `build` both as a directory and a file but the error persists. And yes, I cloned the forked repository there only.

**Comment by jdf** [comment]
Create a new directory somewhere.

```sh
$ mkdir tmp
$ cd tmp
$ git clone https://github.com/jdf/processing.git
$ git clone https://github.com/jdf/processing.py.git
$ cd processing.py
$ ant test
```

**Comment by jdf** [comment]
I have updated the HOWTO to include instructions for fetching my (new) fork of the processing-video project, which should make ll of this work again. Please reopen if I've missed something. Thank you!
