### ISSUE TITLE
Expanding Python library support

### ISSUE THREAD

**Issue by wdyn1** [jdf/processing.py#142]
In trying to get my favorite Python libraries (Requests and BeautifulSoup) to work, I came up with a workaround. 

1) Download Jython 2.7 beta - Standalone Jar from [Jython](http://www.jython.org/downloads.html)
2) Rename to "jython.jar"
3) Replace /Processing/modes/PythonMode/mode/jython.jar with file from step 2
4) Copy package folders from /lib/python2.7/site-packages to Processing sketch folder
5) import requests (or whatever)

Requests works great, but I can't seem to get BeautifulSoup to find a parser other than the standard Python html parser. Any thoughts?

**Comment by jdf** [comment]
Python mode uses a custom-built Jython, with several patches that influence the behavior of numeric types. You can't slip a stock Jython build in.

If you want to use a pure-python (no native code) library, just drop it into your sketch directory.
