### ISSUE TITLE
Slow Loops or Image() ?

### ISSUE THREAD

**Issue by Casyfill** [jdf/processing.py#149]
I am implementing metaballs algorithm with processing.py mode.
As I found, this way my algorithm works drastically slower than the same thing in java mode.

So does it mean that either pixel processing or loops are slower than in java? Is there any chance to improve their perfomance, or It's better anyway to do complex projects in Java Mode?

**Comment by jdf** [comment]
Processing.py will always be extremely slow, relative to Java, in tight loops, such as are typical to rasterizers like the metaball algorithm. It's not the "complexity" per se; it's the number of emulated instructions during the draw() function.
![sorry!](http://i.imgur.com/1ZIojUh.gif)

**Comment by jdf** [comment]
Having said that, you could always design your algorithm in Python mode, then, once you're satisfied with it, implement the slow part in Java, and call your native Java function from the Python sketch.

**Comment by Casyfill** [comment]
That sounds great, but how shall I do that?

**Comment by jdf** [comment]
Ah... that would be a great subject for a tutorial! For now I'll just say that any .jar file that you plunk into your sketch folder is available for use by your sketch. So if you implement, say

```java
package com.casyfill;

public class Banana { /* ... */ }
```

compile it, jar it, place the jar file in your sketch directory, then in your sketch you can

```python
from com.casyfill import Banana

b = Banana()
b.peel()
```

**Comment by Casyfill** [comment]
Oh yeah, tutorial on this would be great,

Would it be correct that I can write  required part as a processing sketch, then save .pde ta as .jar and use it is python?

**Comment by jdf** [comment]
No; `.pde` is Processing source code. A JAR file is a compressed archive of compiled Java, i.e., `.class` files.

**Comment by jdf** [comment]
https://github.com/jdf/processing.py/wiki/How-to-call-%22native%22-Java-code-from-your-Python-Mode-sketch

**Comment by Casyfill** [comment]
Hi Jonathan.
Sorry for bothering, it is  probably just my poor java skills, but I am
getting this error while trying to compile your example java code (from this
example
<https://github.com/jdf/processing.py/wiki/How-to-call-%22native%22-Java-code-from-your-Python-Mode-sketch>
):

warning: [options] bootstrap class path not set in conjunction with -source
1.7

com/example/Example.java:32: error: class, interface, or enum expected



On Wed, Jul 8, 2015 at 9:49 PM, Jonathan Feinberg <notifications@github.com>
wrote:

>
> https://github.com/jdf/processing.py/wiki/How-to-call-%22native%22-Java-code-from-your-Python-Mode-sketch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jdf/processing.py/issues/149#issuecomment-119694907>.
>



-- 
Philipp Kats,
data journalism, analysis and visualization

philipp-kats.squarespace.com <http://cargocollective.com/Cityfish/>


email: casyfill@gmail.com
cellphone: +7(916)438 68 04

**Comment by kazimuth** [comment]
http://stackoverflow.com/questions/12749994/compiler-error-class-interface-or-enum-expected

**Comment by jdf** [comment]
My guess is that you pasted some extraneous characters.



-- 
Jonathan Feinberg  jdf@pobox.com  http://MrFeinberg.com/

**Comment by Casyfill** [comment]
Well, no, I am pretty sure I copy pasted your code ;-/




I actually have to replace your ~Processing/Contents/…  with /Applications/Processing.app/Contents/Java/core.jar  to remove “package does not exist” error, but this warning (warning: [options] bootstrap class path not set in conjunction with -source 1.7) still shows up and (i think so) prevent computer from building a jar (it stops after this line:

adding: com/example/Example.java(in = 710) (out= 332)(deflated 53%))



—

**Comment by Casyfill** [comment]
Sorry for bothering.So, I switched to: javac -source 1.8 -target 1.8 … (as I am using JDK8)







and I also had to replace "/tmp/example.jar" with “example.jar”, couse for some reason It did not want to create file otherwise (i have a guess it should be “tmp/example.jar maybe “. This way jar was created, but now Python mode throws me “no module named example” thing...


—

**Comment by Casyfill** [comment]
Ah ok.I had to update python mode and make it  javac -source 1.7 -target 1.7 still replasing ’/tmp/example.jar’. 




Now it works. Thank you!


—

**Comment by Casyfill** [comment]
then, probably, a very stupid one:




It is all nice, but what shall I do if I want to define colors in Java for each pixel?

is there any lib, or it is easier to rewrite everything in java_Processing?


—

**Comment by jdf** [comment]
This might be a better question for the general processing forums, and not for this project.
