### ISSUE TITLE
Constructed applet does not work

### ISSUE THREAD

**Issue by Casyfill** [jdf/processing.py#150]
nothing happens after the processing.py/initilalisation window dissapears

I guess it started after I added 'Isolines' library

**Comment by Casyfill** [comment]
Ok, I've got it: running the main file inside package (in Mac) opens terminal, and as it was said there, program aborted because I asked it to import a tab I've deleted. So I fixed that, but there should be a better way to avoid this type of things

**Comment by kazimuth** [comment]
It didn't crash when you tried to run it in the editor?

**Comment by Casyfill** [comment]
nope. But maybe thats was kept int operational memory

**Comment by kazimuth** [comment]
Were you using anything from the file or just importing it?

**Comment by Casyfill** [comment]
No i did not



—

**Comment by kazimuth** [comment]
Huh. I'm pretty sure we delete all user-defined stuff when an applet finishes running in the editor, but I guess we don't clear out some sort of filename cache.
