### ISSUE TITLE
using pip with processing.py

### ISSUE THREAD

**Issue by kylemcdonald** [jdf/processing.py#152]
if i open my terminal and type:

```
$ python
>>> import numpy
>>> 
```

it works ok. but if i type `import numpy` into a processing.py tab, i get `processing.app.SketchException: ImportError: No module named numpy`.

i know processing.py has its own interpreter (jython) and libraries that it's using, but is there any way to tell processing.py to also use the same libraries available from the terminal?

alternatively, is there a way to install libraries for processing.py with pip or easy_install?

**Comment by jdf** [comment]
Two unrelated problems here:

1. You can't use CPython libraries with processing.py, which is implemented in Java.
1. processing.py doesn't know anything about your system Python installation, and doesn't use it in any way.

**Comment by kylemcdonald** [comment]
thanks, i was suspecting both of those things.

i think my misunderstanding comes from familiarity with p5.js, which is a new implementation of processing in js. i didn't realize that processing.py is not a new implementation, but a wrapper. this is amazing because it makes the processing environment and libraries available to python programmers, but unfortunately it means the entire python ecosystem is inaccessible.

an alternative approach is offered by https://pypi.python.org/pypi/pyprocessing but it seems like development stalled in 2012. having the freedom to use processing.py in this way would be incredible, but now that i understand it, it seems like a very different project.

**Comment by tildebyte** [comment]
There's some nuance here. Most anything written in **pure python** will run if imported into a sketch. I usually work from the command line, so it's a little different in the PDE (you can use `add_library`, but `import` statements should work as well). Getting jython to *find* python libs is the challenge. I can tell you that anything (again, **pure python**) in the sketch directory should import OK.

I hope that didn't make things *more* confusing.
