### ISSUE TITLE
command line arguments?

### ISSUE THREAD

**Issue by velkyel** [jdf/processing.py#153]
Is there any simple way how to read/pass command line arguments in script? I've tried

```
$ ./processing-py.sh test.py foo bar
```

but test.py:

```
import sys

def setup():
    print(sys.argv)
    noLoop()
```

always print ['--noredirect', 'test.py'] only,

thanks

**Comment by jdf** [comment]
No, there isn't. But there ought to be!

When I next have time to work on it, I'll put my mind to it.

I'd welcome a pull request, if you want to give it a shot.

**Comment by b-jufre** [comment]
When I try to run "./processing.py mysketch.py" it throws and error that says: "Error: Unable to access jarfile"

**Comment by Inokinoki** [comment]
Hi, I'm trying to add the command line arguments support.
I noticed that in `Runner.java` in latest version, arguments for Python interpreter is same as PAppletArguments.
```Java
    final String[] args = sketch.getPAppletArguments();

    PythonInterpreter.initialize(null, props, args);
```
Are they really useful for Python Interpreter ? 
I mean that could I do some works here to add command line support ?
Sincerely

**Comment by jdf** [comment]
Because I only support Python Mode now, and not the command-line version of python Processing, I will not accept any pull requests for the command line.

**Comment by Inokinoki** [comment]
Thanks for your reply.
Then it will be only for my own use.

Jonathan Feinberg <notifications@github.com> 于 2018年12月14日周五 18:59写道：
