### ISSUE TITLE
Python mode is disabled

### ISSUE THREAD

**Issue by gtalarico** [jdf/processing.py#155]
I just installed processing and the option to install python mode is disabled:

![image](https://cloud.githubusercontent.com/assets/9513968/9540719/bf6e9344-4d2f-11e5-85b1-c382a9d21dcf.png)

**Comment by jdf** [comment]
Yes; Python Mode is not compatible with Processing 3.

**Comment by gtalarico** [comment]
Thanks jdf.
It may be helpful for others if we can add a note about this in the py.processing.org page. 
I will drop this suggesting in the processing-py-site github.
