### ISSUE TITLE
Python mode for Processing 3.0

### ISSUE THREAD

**Issue by irlabs** [jdf/processing.py#156]
Obviously since Processing is officially moving to **3.0**, so should all of its tools, modes and libraries.
Is porting python mode to 3.0 already in the pipeline?

https://github.com/processing/processing/wiki/Changes-in-3.0
https://github.com/processing/processing/releases

**Comment by jdf** [comment]
There is a [GSoC](https://developers.google.com/open-source/gsoc/) project underway that gets us about 75% of the way there. I'll be reviewing and accepting those patches soon. There will still be a good deal of hard work to do after that, and I can't say how long it will take. The 3.0 changes are very difficult to adapt this mode to.
