### ISSUE TITLE
P5.3 integration: '_ast.Attribute' object has no attribute 'id' in multiple sketches

### ISSUE THREAD

**Issue by tildebyte** [jdf/processing.py#160]
The path specifiers are relative to the top level of the mode examples.
The lines specified are the ones where the PDE stopped.
**Topics/Fractals and L-Systems/PenroseTile**, **Pentigree**, **PenroseSnowflake**: Main `.pyde` file, calling "LSystem" object's (they are named differently in each sketch) `render()` in `draw()`
**Topics/Simulate/Chain**: Calling `Spring2D.update()`
**Demos/Graphics/BoxClock**: Line 45, calling `scale()`

The full traceback:
````java
processing.app.SketchException: AttributeError: '_ast.Attribute' object has no attribute 'id'
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(Unknown Source)
	at jycessing.mode.run.SketchRunner.access$300(Unknown Source)
	at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by tildebyte** [comment]
I'll add more sketches if/when I come across them.

**Comment by jdf** [comment]
Minimal repro case?

**Comment by tildebyte** [comment]
Sorry about that, offline for a few days.
