### ISSUE TITLE
mousePressed() triggered before setup() is complete

### ISSUE THREAD

**Issue by GoToLoop** [jdf/processing.py#170]
In Java Mode, any triggered events are called back only after **setup()** had finished and **draw()** run once!
But after helping out some1 @ https://forum.Processing.org/two/discussion/14685/oscp5-in-python-mode,
I've just found out I had to include some **globals()** test before allowing **mousePressed()** to proceed.   :-(
Otherwise, if any1 clicked too soon, while the program was still in **setup()**, sketch would crash!  =(  

``` Processing
# OscP5 Python Conversion (v2.21)
# forum.Processing.org/two/discussion/14685/oscp5-in-python-mode
#2016-Jan-30

add_library('oscP5')

def setup():
    size(600, 400)
    noLoop()
    frameRate(25)

    global osc, loc, msg
    osc = OscP5(this, 12000)
    loc = NetAddress('127.0.0.1', 12000)
    msg = OscMessage('/test')


def draw():
    background(int(random(PImage.ALPHA_MASK)))
    frame.setTitle(`frameCount`)


def mousePressed():
    if 'osc' not in globals(): return

    msg.clearArguments()
    msg.add(123)
    osc.send(msg, loc)

    print msg
    redraw()


def oscEvent(osc, msg):
    print "### Received an Osc message."
    print "AddrPattern: %s" % msg.addrPattern()
    print "TypeTag: %s" % msg.typetag()
    redraw()
```

**Comment by jdf** [comment]
I'm going to close this because the repro case is too complicated. If you can come up with a minimal test case that demonstrates the problem, please reopen.
