### ISSUE TITLE
Add Feature: Line numbers in python mode

### ISSUE THREAD

**Issue by Prabhnith** [jdf/processing.py#174]
the line numbers are really helpful, add them to the python mode too.

**Comment by jdf** [comment]
Is this a feature of Java mode in Processing?

**Comment by JokerQyou** [comment]
@jdf Yes it is. I just downloaded Processing 3 for Windows, and there are line numbers on the left (Java mode is the default and only mode pre-installed). I'm attaching a screenshot.
![image](https://cloud.githubusercontent.com/assets/1465267/16860390/6352c696-4a6a-11e6-8477-4b41f416cae2.png)

**Comment by benfry** [comment]
If someone is interested in implementing this, the next release of Processing (the current source in the repo) pushes the line number handling and other generally useful features out of the Java Mode and into `Editor` and more general classes like `PdeTextArea` and others.

**Comment by jdf** [comment]
Great news, @benfry.

**Comment by benfry** [comment]
Processing 3.2, probably arriving in the next couple days once the dust settles.

**Comment by villares** [comment]
Can we have line numbers now p-p-p-p-please? :))

**Comment by jdf** [comment]
Yes! Pushed to build 3022.
