### ISSUE TITLE
Sketch window Title is not proper in Python mode

### ISSUE THREAD

**Issue by Prabhnith** [jdf/processing.py#177]
In java Mode:
![original](https://cloud.githubusercontent.com/assets/11560449/13026984/d78fef96-d262-11e5-97b1-a7b9dac04078.png)

In Python Mode:
![papplet jython driver](https://cloud.githubusercontent.com/assets/11560449/13026985/d83d6a86-d262-11e5-8fed-b8c4f0e96b8d.png)

**Comment by jdf** [comment]
Pushed in build 3007.
