### ISSUE TITLE
Neither exit() nor ESC key fully kills sketch under OpenGL renderers

### ISSUE THREAD

**Issue by GoToLoop** [jdf/processing.py#191]
By using renderers P2D or P3D, either hitting ESC or explicitly invoking **exit()**, don't close sketch's window.
Instead, it minimizes its window. However there's no sketch running on it anymore. Just a black canvas.

Both renderers JAVA2D & FX2D behaves as expected, fully closing the window.
Although under FX2D, PDE's "Play" button still remains green even after it's closed.

Another glitch I've noticed is that Python Mode creates 2 "java.exe" processes.
We can close both via the Task Manager. But after running anything, at least 1 stays permanently open.
Even after changing to another mode, like Java or JS modes, those "java.exe" processes still linger!

Anyways, here's some sketch demoing the OpenGL renderers' bug.
We can either await the countdown or prematurely hit ESC. Result is the same. Minimized window!

```python
#RENDERER = JAVA2D
#RENDERER = FX2D
RENDERER = P2D
#RENDERER = P3D

def setup():
    size(250, 200, RENDERER)
    smooth(8)
    frameRate(1.0)

    fill(0xffFFFF00)
    textAlign(CENTER, CENTER)
    textSize(200)


def draw():
    background(50)
    countdown = 11 - frameCount
    text(countdown, width>>1, height>>1)
    countdown or exit()
```

P.S.: Running 64-bit Processing v3.0.2 under Win7. However no glitch under 64-bit Processing v2.2.1.

**Comment by jdf** [comment]
Thanks for the very helpful bug report.

Yes, it appears that the internals of the Processing run loop has not only changed again, but behaves differently for different renderers. I will get to it when I can, but it's likely to be a long and tedious process.

**Comment by jdf** [comment]
Fixed by 8d7834bc9d8b7fc135f2c387d2196b148f90ed40, and pushed to build 3005.

**Comment by jdf** [comment]
Note that any sketch that uses JavaFX will take a long time to start up because the sketch runner process cannot be recycled, because JavaFX is terrible.

**Comment by GoToLoop** [comment]
Gr8 job! Now I can simply hit ESC rather than always needing to click at the window X button!  :D

> Note that any sketch that uses JavaFX will take a long time to start up...

Is it after the fix? B/c for me, FX2D renderer opens relatively quick.
It's OpenGL based renderers like P2D & P3D which take a longer time to come up.
Of course, JAVA2D is the most stable renderer even in P3!  :P

**Comment by jdf** [comment]
Yes. In order to close the window in JavaFX, I have to destroy the sketch runner process.
