### ISSUE TITLE
`open()` with write mode creates files in strange places

### ISSUE THREAD

**Issue by aparrish** [jdf/processing.py#192]
```
import os
print os.getcwd()
fh = open("foo.txt", "w")
fh.write("hello1234\n")
fh.close()
```

The expected behavior of this (I think?) would be to create a file called `foo.txt` in the sketch directory. The actual behavior is that it creates a file in the *current working directory*, which in my case was something incomprehensible like 

    /private/var/folders/8r/3pg241bn1kvbv_hgjl31dyzxxxxxgp/T/sketch_160306c2367187332000000272

This happens whether or not the sketch folder is a temporary folder (i.e., even if I've previously saved the sketch). The current working directory reported by `os.getcwd()` is *not* the same directory that opens when you go to Sketch > Show Sketch Folder.

(I discovered this while going over previously-verified code examples for *Getting Started with Processing.py*, so I'm reasonably sure `open()` had the expected behavior some time in the near past... maybe something changed in Processing 3?)

Build 3005 of Python Mode, running with Processing 3.0.2 on OSX 10.11.3

**Comment by jdf** [comment]
Hmm. I'm not sure what to do about that.

When the sketch changes, but hasn't yet been saved, I copy the whole kit and kaboodle to a temp directory, as you've discovered. The sketch directory has to be the current working directory in order for normal Python loading semantics to work as expected.

Do you think that if I detect newly created files, and copy them into the the sketch folder on sketch termination, that that would do it? Any other ideas?

**Comment by jdf** [comment]
Wait, now I see your comment that this happens even when the sketch is not dirty, which is definitely unintended. I'll see if I can reproduce it.

**Comment by jdf** [comment]
Also, nice to hear from you! I'm glad to hear that the Getting Started project is still real. :)

**Comment by jdf** [comment]
I can't reproduce the problem that running a clean (i.e., unchanged since the last save) sketch causes a temp copy of the sketch to be made. When I save the sketch, then run it, it runs in the sketch folder as expected.

Can you provide steps to reproduce?

**Comment by aparrish** [comment]
Yeah, okay, it looks like it works correctly if (a) you've (ever) saved the sketch and (b) you haven't made any changes since the last save. (That probably explains why it worked for me before—I must have been saving diligently, instead of what I was doing earlier today, which was just pasting in one example after another into from the book into the same sketch to make sure they work, without saving.)

Notably, using the `PrintWriter` class works just fine, even in a "dirty" sketch:

```
writer = createWriter("foo.txt")
writer.println("hello1234")
writer.flush()
writer.close()
```

There's already [some magic in core.py](https://github.com/jdf/processing.py/blob/eb8451e43a977bb1b48a3542595714022a08df8e/runtime/src/jycessing/core.py#L584) to get Python's `open()` to look for files in the sketch path and data path, but that logic looks like it's based on checking to see if the file already exists, which obviously sometimes won't be the case if you're opening the file for writing. So maybe that logic could be made aware of the mode flag and open the file in the "real" sketch folder accordingly? Although that would be surprising to someone who is *expecting* `open()` to write the file in the *actual* current working directory.

Honestly now that I'm thinking about it, the solution might be as easy as just exposing the Processing built-in `sketchPath()`, which seems to report the temp folder of the "clean" (?) sketch, not the temp folder that the dirty sketch is running in. Right now `sketchPath()` isn't patched into the builtins in `core.py` but you can still call it through `this`:

```
import os
print os.getcwd()
print this.sketchPath("")
```

And *this* code does exactly what I expect it to, whether the sketch is dirty or clean:

```
fh = open(this.sketchPath("foo.txt"), "w")
fh.write("hello1234\n")
fh.close()
```

I wouldn't mind having to write `open(sketchPath("foo.txt"), "w")` and it's not that hard to explain `sketchPath()` as a concept in the book even for just a one-off example... thoughts?

And yes, the book is still a thing! Going through the final edits now. Also, I've been meaning to get in touch with you about some ideas relating to my Processing foundation fellowship... expect an e-mail from me soon.

**Comment by jdf** [comment]
It's a good idea, but `sketchPath` is private API, not documented in the Processing reference.

Having now done some reading... the "Processing way" is to use `createWriter`. On the other hand, that seems silly, to construct an explicitly Java IO thingy just to do something that's otherwise a no-brainer in Python.

So, maybe we should indeed expose sketchPath and leave it at that. If Ben & co. decide to nuke sketchPath entirely, I'd just have to implement it myself, which is no big deal. I do wonder why they don't expose it.

@benfry do you care to comment?

**Comment by jdf** [comment]
All right. Given the lack of input from the Processing project, I'll hereby executively decide to expose sketchPath.

**Comment by aparrish** [comment]
thank you! that actually makes another thing I was working on way easier (getting python mode to play friendly with pip/virtualenv)

**Comment by jdf** [comment]
Deployed to build 3006.
