### ISSUE TITLE
PVectors and Classes

### ISSUE THREAD

**Issue by pybissell** [jdf/processing.py#193]
Getting "Nonetype object as no attribute X" on the ellipse (self.position.x, ....) line.  My novice-status keeping me from understanding if this is an error in my Python or the interaction with it and Processing. 
I checked some of the python-based examples and found limited examples of where a PVector is used. The "Basics" examples don't use classes at all. I found a couple of things in the Demos and Topics that confirmed self.position.x is a valid reference to a PVector's first position but also found that other demos fail in a similar error (for example demo "Chain" also gives the same "Nonetype object has no attribute" error). Would love to help translate the easier PVector java demos into Python but until I know what I am doing wrong, I'm stuck.
`class Ball():
    
    position = PVector
    velocity = PVector
    
    def __init__(self):
        self.position = PVector(random(640), random(480))
        self.velocity = PVector(random(-2,3), random(-3,3))
        
    def move(self):
        self.position = self.position.add(self.velocity)
        
    def show(self):
        fill(128)
        ellipse(self.position.x, self.position.y, 30,30)`

**Comment by jdf** [comment]
`PVector.add` adds in-place, and does not return a new `PVector`. You're assigning `None` to `self.position` when you assign the value of `PVector.add` to it.

Also, the first two lines in your example don't do anything. They are assigning the PVector class itself to the variables `position` and `velocity`.

**Comment by pybissell** [comment]
<embarassed emoji here>
Thank you 
AND…
Thank you so much for the work you have done on this project. Processing is a true gift to tinkerers and those who want to explore math in a visual sense (I fall into that category). I appreciate your work and those who work on projects such as these.

Dr. Paul Bissell

**Comment by jdf** [comment]
Thank you very much for your kind word. I hope Python Mode brings more pleasure than pain!
