### ISSUE TITLE
How to use the microphone with processing.py ?

### ISSUE THREAD

**Issue by valentinlageard** [jdf/processing.py#194]
I tried with the original sound library and with pyAudio but the two seems to not work. Is there an alternative or is it still a limitation due to Jython ?

**Comment by jdf** [comment]
I translated the input demo from the Processing sound library into Python, and it worked fine for me.

```python
add_library('sound')

scale = 1

def setup():
    size(640, 360)
    background(255)

    # Create an Audio input and grab the 1st channel
    global input
    input = AudioIn(this, 0)

    #  start the Audio Input
    input.start()

    #  create a new Amplitude analyzer
    global rms
    rms = Amplitude(this)

    #  Patch the input to an volume analyzer
    rms.input(input)

def draw():
    background(125, 255, 125)

    #  adjust the volume of the audio input
    input.amp(map(mouseY, 0, height, 0.0, 1.0))

    #  rms.analyze() return a value between 0 and 1. To adjust
    #  the scaling and mapping of an ellipse we scale from 0 to 0.5
    scale = int(map(rms.analyze(), 0, 0.5, 1, 350))
    noStroke()

    fill(255, 0, 150)
    #  We draw an ellispe coupled to the audio analysis
    ellipse(width / 2, height / 2, 1 * scale, 1 * scale)
```

**Comment by valentinlageard** [comment]
Thanks for the reply and sorry for the disturbances.

Then maybe it's the FFT analyzer that poses problem :
`add_library('sound')
import math, random

def setup():
    background(0)
    size(800, 600)
    global fft, spectrum, input
    fft = FFT(this, 512)
    input = AudioIn(this, 0)
    input.start()
    input.amp(0.9)
    fft.input(input)
    spectrum = [0.0]*512

def draw():
    global fft, spectrum, input
    background(0)
    stroke(255)
    fill(100)
    
    input.amp(1)
    test = fft.analyze(spectrum)
    
    println(test)`

This prints only `None`

If I try to print `spectrum`, it's only a list of zeros :(
P.S. : Pardon my english mistakes if there are any.

**Comment by jdf** [comment]
I don't see where you assign anything to spectrum other than 512 0s.

**Comment by jdf** [comment]
Oh, I see.

Probably you need to give `FFT` a real Java array of floats, and not a Python sequence.

Try

```python
import jarray

# then, in setup()
spectrum = jarray.zeros(512, 'f')
```

**Comment by valentinlageard** [comment]
It doesn't work, spectrum is now a jarray of zeros and test returns `None`...

**Comment by valentinlageard** [comment]
Maybe i have to convert test into a python array ?

**Comment by jdf** [comment]
The `analyze` function is void, which is why you're printing out None. 

I translated the example program verbatim, and get the expected result:

```python
add_library('sound')
import jarray

spectrum = jarray.zeros(512, 'f')

def setup():
    size(512, 360)
    background(255)
    global fft, input
    fft = FFT(this, 512)
    input = AudioIn(this, 0)
    input.start()
    fft.input(input)

def draw():
    background(255)
    fft.analyze(spectrum)
    for i, band in enumerate(spectrum):
        line(i, height, i, height - band * height * 5)
```

**Comment by valentinlageard** [comment]
Thanks a lot. Java is quite obscure to me and the mix between java and python is quite disturbing. But thanks for your time anyway :)

**Comment by jdf** [comment]
Glad to have helped. It's good to see where the difficult points are.

**Comment by yonghuming** [comment]
> I translated the input demo from the Processing sound library into Python, and it worked fine for me.
> 
> ```python
> add_library('sound')
> 
> def setup():
>     size(640, 360)
>     background(255)
> 
>     # Create an Audio input and grab the 1st channel
>     global input
>     input = AudioIn(this, 0)
> 
>     #  start the Audio Input
>     input.start()
> 
>     #  create a new Amplitude analyzer
>     global rms
>     rms = Amplitude(this)
> 
>     #  Patch the input to an volume analyzer
>     rms.input(input)
> 
> def draw():
>     background(125, 255, 125)
> 
>     #  adjust the volume of the audio input
>     input.amp(map(mouseY, 0, height, 0.0, 1.0))
> 
>     #  rms.analyze() return a value between 0 and 1. To adjust
>     #  the scaling and mapping of an ellipse we scale from 0 to 0.5
>     scale = int(map(rms.analyze(), 0, 0.5, 1, 350))
>     noStroke()
> 
>     fill(255, 0, 150)
>     #  We draw an ellispe coupled to the audio analysis
>     ellipse(width / 2, height / 2, 1 * scale, 1 * scale)
> ```

but how to install sound library?

**Comment by villares** [comment]
> but how to install sound library?

Hi @yonghuming,

You'll will install it from the `Add Library...` panel found in the `Import Library...` item in `Sketch` menu of the Processing IDE
