### ISSUE TITLE
Possible `add_library('pdf')` line missing in the file "examples.py/Library/PDF Export/OneFrame.py"

### ISSUE THREAD

**Issue by indranilsinharoy** [jdf/processing.py#198]
I tried the "One Frame" example at [processing.py/examples.py/Library/PDF Export/OneFrame.py](https://github.com/jdf/processing.py/blob/master/examples.py/Library/PDF%20Export/OneFrame.py), and saw that the PDF library is not imported, which resulted in an error in my Windows machine. Should we not include the line `add_library('pdf')` at the beginning?  

My environment is Windows 7, 64 bit.

**Comment by jdf** [comment]
`add_library` is only for Python Mode, and not for the standalone sketch runner.

**Comment by indranilsinharoy** [comment]
Hi @jdf ,

I am sorry, I probably have not understood something (I am very new to Processing). I understand that `add_library` is for the Python mode. Do you mean the rest of the code at  [processing.py/examples.py/Library/PDF Export/OneFrame.py](https://github.com/jdf/processing.py/blob/master/examples.py/Library/PDF%20Export/OneFrame.py) can run outside of Python mode? 

(You don't have to answer the question if you don't have time. That's alright!)

Thanks.

**Comment by jdf** [comment]
examples.py is not for Python Mode. Those are sketches for the command-line sketch runner that preceded Python Mode.

There is no such thing as `add_library` in the standalone python sketch runner.

**Comment by indranilsinharoy** [comment]
Got it. Thank you @jdf.
