### ISSUE TITLE
How can I use Pyserial with Python Mode

### ISSUE THREAD

**Issue by mjs513** [jdf/processing.py#200]
Subject really says it all. I want to use pyserial as opposed to processing serial but when I do an import I get a module not found.

Thanks
Mike

**Comment by jdf** [comment]
Python Mode doesn't use your system Python installation. You'll have to copy whatever (pure python) library you'd like to use into your sketch folder.

**Comment by mjs513** [comment]
Hi jdf,
Thanks for getting back to me.

Test 1:  I copied all the files in pyserial (including subdirectories) and put it into the sketchbook folder (not a separate code folder) but I am still getting the same error message - no module named serial.  Here's the entire error message:

> processing.app.SketchException: ImportError: No module named serial
> 	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:248)
> 	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:227)
> 	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:122)
> 	at java.lang.Thread.run(Thread.java:745)


Test 2. I then just copied the serial folder to sketchbook and I get the following error:

> processing.app.SketchException: import * does not work in this environment.

Any and all help would be appreciated.

Mike

**Comment by jdf** [comment]
The second error message is correct; you can't `from foo import *` in Python Mode.

**Comment by mjs513** [comment]
Ok so now what do I do to get this to work. I just tried the following but it still gave me the same error.  Really what I need is the timeout to work which processing serial does not have available.
```
import serial.Serial
import serial.flushInput
import serial.flushOutput
import serial.clear
import serial.Serial.exception
import serial.timeout
import serial.inWaiting
import serial.busy
import serial.open
import serial.read
import serial.write
import serial.sendBreak
import serial.setBreak
import serial.setRTS
import serial.setDTR
import serial.setCTS
import serial.setCTR
import serial.setCD
import serial.setCTR
import serial.device
import serial.close
import serial.read
```

**Comment by jdf** [comment]
Could you create a minimal example program that demonstrates the problem, and provide steps to install the library in question?

**Comment by mjs513** [comment]
To install the library I copied the serial directory from Python site-packages directory to the sketch folder per our earlier discussion. If I just use import serial I get the same error. The one thing I noticed in the serial directory there is a lot of serialxxx.py files - can it be getting confused on which one to use.

 Here is a simple example that throws the error:

```
import  time, datetime, optparse, signal, sys

import serial.Serial
import serial.flushInput
import serial.flushOutput
import serial.clear
import serial.Serial.exception
import serial.timeout
import serial.inWaiting
import serial.busy
import serial.open
import serial.read
import serial.write
import serial.sendBreak
import serial.setBreak
import serial.setRTS
import serial.setDTR
import serial.setCTS
import serial.setCTR
import serial.setCD
import serial.setCTR
import serial.device
import serial.close
import serial.read

def connect():
   # create serial port object
    try:
        ser = serial.Serial(port=options.port, baudrate=options.baud, timeout=1, writeTimeout=1)
    except serial.SerialException as e:
        print("\n================================================================")
        print("Port error (name='%s', baud='%ld'): %s" % (options.port, options.baud, e))
        print("================================================================")
        exit(2)

    # flush buffers
    ser.flushInput()
    ser.flushOutput()
    
def setup():
    size(640, 360)
    connect()
    
def draw():
    background(204)
```

**Comment by jdf** [comment]
Hmm. When I try I get a different exception

`ImportError: No Java Communications API implementation found`

which suggests that the Mac's JRE doesn't have either of the implementations that pyserial looks for https://github.com/pyserial/pyserial/blob/master/serial/serialjava.py#L37 .

**Comment by jdf** [comment]
The Processing serial library is a simplified wrapper around the https://github.com/scream3r/java-simple-serial-connector java library. Perhaps you could drop a build of that into your sketch and use that API directly? They seem to support timeouts in their API. Another long-term option would be to submit a patch to the Processing serial library, but they move rather slowly.

**Comment by mjs513** [comment]
A real neophyte here, so when u say build u mean i should create a jar and
dump it into the sketch folder? How do I then reference it under python
mode?

**Comment by jdf** [comment]
Yes, you'll want a jar file of the library in the sketch folder.

Then you'll use Jython techniques to refer to the library. The documentation is at http://www.jython.org/jythonbook/en/1.0/JythonAndJavaIntegration.html, but, in general, if you want to use the class `com.foo.Whatever`, then you'll

```python
from com.foo import Whatever

w = Whatever("banana", 12.2)
w.doSomething()
```

**Comment by mjs513** [comment]
Thanks jdf. Appreciate the help. Guess i have another project to work on :)

**Comment by koniho** [comment]
I wrote a simple wrapper around Processing's Serial class to provide a pyserial-like interface some time ago. I haven't spent any further time refining but it worked out-of-the-box in re-using existing python code that used pyserial in `processing.py`

I haven't spent the time to determine where this might live in `processing.py` so feel free to use/commit/whatever.

The contents below were placed in a file named `serial.py` in the sketchbook directory. 

```processing
add_library("serial")

import os
import sys
import time

from processing.serial import Serial as PSerial

class Serial(object):
    """
    A wrapper around processing.serial.Serial to provide a
    PySerial.Serial like interface to a serial port. 
    """
    def __init__(self, port, baudrate=9600, *args, **kwargs):
        print "Baudrate: %d" % (baudrate)
        self._pserial = PSerial(this, port, baudrate)
        self.port = port
        self.baudrate = baudrate
        self._is_open = True
        
    def _data_to_str(self, data):
        # pyserial read() returns strings 
        return "".join([chr(i) for i in data])
        
    def read(self, size=1):
        bytes_read = []
        start_time = time.time() 
        
        while len(bytes_read) < size:
            if self.inWaiting() > 0:
                val = self._pserial.read()
                
                if val != -1:
                    bytes_read.append(val)
                    
            if time.time() - start_time > self.timeout:
                break

        return self._data_to_str(bytes_read)
    
    def write(self, s):
        for c in s:
            self._pserial.write(c)
            
        return len(s)

    def inWaiting(self):
        return self._pserial.available()

    def flush(self):
        return self._pserial.clear()
    
    def flushInput(self):
        return self._pserial.clear() 

    def open(self):
        if not self._is_open:
            self._pserial = PSerial(this, self.port, self.baudrate)

    def close(self):
        self._is_open = False
        return self._pserial.stop()

    def isOpen(self):
        return self._is_open
    
class SerialException(Exception):
    pass
```

**Comment by mjs513** [comment]
@koniho the wrapper works like a charm.  Like you said it worked right out of the box.  You are a life saver.  Now I can debug the rest of the program :)

Mike
