### ISSUE TITLE
Execute / compile sketch form command line

### ISSUE THREAD

**Issue by b-jufre** [jdf/processing.py#203]
@jdf I apologize beforehand if this topic has been touched.

First of all thank you for all the effort you put in this project. With the previous version you could execute / compile your sketches from the command line. Which made possible to use any IDE other than the Processing environment.

But since the new version, there's not ".jar" executable, is there a way to do so even without the ".jar" executable?

**Comment by jdf** [comment]
Duplicate of #153.
