### ISSUE TITLE
import javax.sound.midi doesn't work

### ISSUE THREAD

**Issue by aparrish** [jdf/processing.py#204]
A Python Mode sketch with the following code:

    import javax.sound.midi;

...fails with the following error:

```
processing.app.SketchException: ImportError: No module named sound
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:247)
	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:226)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:121)
	at java.lang.Thread.run(Thread.java:745)
```

The equivalent Java Mode sketch (`import javax.sound.midi.*;`) works without incident, as does importing other Java libraries in Python Mode (e.g., `from java.lang import Object`).

Weirdly, if I first add (e.g.) [the MidiBus library](http://www.smallbutdigital.com/themidibus.php), then the import *does* work. Installing the MidiBus and running the following sketch works:

```
add_library('themidibus')
import javax.sound.midi;
```
(and I can even go on to use all of the javax.sound.midi-related functionality I want). Thoughts?

**Comment by jdf** [comment]
I'm surprised that it ever works at all; I'm not even sure what it means when it does work.

You have to

```python
from javax.sound.midi import MidiChannel
from javax.sound.midi import Synthesizer
```

etc.

**Comment by aparrish** [comment]
ah okay, got it. will add this to my list of stuff to add to the documentation.
