### ISSUE TITLE
TheMidiBus library doesn't work

### ISSUE THREAD

**Issue by aparrish** [jdf/processing.py#205]
This is actually what occasioned my reporting #204. The following sketch produces no output:

```
add_library('themidibus')
def setup():
    MidiBus.list()
```

The equivalent Java Mode sketch merrily produces a list of devices:

```
import themidibus.*;
void setup() {
  MidiBus.list();
}
```

**Comment by jdf** [comment]
Hmm.

**Comment by jdf** [comment]
I wonder how list() produces its output... Is there a way to retrieve the list and examine it, rather than printing it?

**Comment by jdf** [comment]
Yeah, 

```python
add_library('themidibus')

for m in MidiBus.availableInputs():
    print "%s" % m
```

produces

```
Real Time Sequencer
```

on my Mac.

**Comment by jdf** [comment]
Oh, actually, the `list()` function works fine on my box in Python Mode, too.

**Comment by aparrish** [comment]
okay, weird. digging in and looking through the inputs works for me too. not sure what's going on here.

**Comment by aparrish** [comment]
I realized that I was running an out-of-date build of Python Mode. after updating, everything works fine... apologies for the false alarm!
