### ISSUE TITLE
support TheMidiBus callbacks

### ISSUE THREAD

**Issue by aparrish** [jdf/processing.py#206]
[TheMidiBus](http://www.smallbutdigital.com/themidibus.php) is the only 3rd-party Processing library that comes up in a search for "midi" in the "Add Tool..." dialog. It's currently impossible to use this library because of the introspection issues mentioned in #201. Moreover, as far as I can tell there's no easy pure Python alternative for accessing MIDI devices. So it would be nice if Python Mode supported this out of the box!

**Comment by jdf** [comment]
Unless I misunderstand, the midi bus library already accepts objects that implement any of several interfaces for callbacks, not merely the PApplet. For example, I'd expect this to work:

```python
add_library('themidibus')


class PyMidiListener(SimpleMidiListener):
    def noteOn(channel, pitch, velocity):
        print "ON: %d %d %d" % (channel, pitch, velocity)
        
    def noteOff(channel, pitch, velocity):
        print "OFF: %d %d %d" % (channel, pitch, velocity)

    def controllerChange(channel, number, value):
        print "CONTROLLER: %d %d %d" % (channel, number, value)

def setup():
    MidiBus.list()
    global mb
    listener = PyMidiListener()
    mb = MidiBus()
    mb.addMidiListener(listener)
    mb.addInput(0)

def draw():
    pass
```

Does it not? (I don't have ready access to Midi gear to test.)

**Comment by aparrish** [comment]
It does not, though I agree that from looking at the theMidiBus source code, it seems like it should...? for reference, here is a working Java Mode sketch to send MIDI notes and controller changes on the built-in bus (no equipment required):

```
import themidibus.*;
MidiBus myBus;

void setup() {
  size(400, 400);
  background(0);
  MidiBus.list();
  myBus = new MidiBus(this, -1, 1); // set third parameter to index of "Bus 1" on OSX 
}

void draw() {
  background(0);
}

void mousePressed() {
  println("sending note on");
  myBus.sendNoteOn(0, 64, 64);
}

void mouseReleased() {
  println("sending note off");
  myBus.sendNoteOff(0, 64, 64);
}

void keyPressed() {
  println("sending controller change");
  myBus.sendControllerChange(0, 0, key);
}
```

... and here is a working Python Mode sketch that uses `javax.sound.midi` directly to receive MIDI on the bus:

```
from javax.sound.midi import MidiSystem, Receiver

def getMidiDevices():
    devices = MidiSystem.getMidiDeviceInfo()
    inputs = list()
    outputs = list()
    for dev in devices:
        midi = MidiSystem.getMidiDevice(dev)
        # get outputs
        if midi.getMaxReceivers() != 0: #(-1 or positive)
            outputs.append(midi)
        if midi.getMaxTransmitters() != 0:
            inputs.append(midi)
    return (inputs, outputs)        

class MidiReceiver(Receiver):
    def __init__(self, callback):
        print "hi?"
        self.callback = callback
    def send(self, message, timeStamp):
        self.callback(message.getMessage())
    
def setup():
    size(400, 400)
    devices = getMidiDevices()
    print [[dev.getDeviceInfo() for dev in devs] for devs in devices]
    device = devices[0][0] # set second index to "Bus 1" on OSX
    recv = MidiReceiver(on_message)
    device.getTransmitter().setReceiver(recv)
    device.open()
        
def draw():
    pass
    
def on_message(message):
    print message
```

If I have both of these sketches running at once on OSX, I can successfully receive the messages sent from the Java Mode sketch in the Python Mode sketch.

It may be that the answer here is "theMidiBus is not supported in Python Mode, use javax.midi.sound directly," which is fine—I can write up a tutorial for that! But I do think that it would be easier for quick sketches if the theMidiBus library and its callbacks were supported directly...

**Comment by jdf** [comment]
No, no; we'll make it work. Hang in there. :)

**Comment by yougop** [comment]
Any progress on this subject? Would be so nice to have themidibus library working. javax.sound.midi works, but is lot more complicated for processing.py users like me. Thanks a lot in advance, Volker

**Comment by jdf** [comment]
Fixed in build 3025.
