### ISSUE TITLE
Python Mode incompatible with Processing 3.2

### ISSUE THREAD

**Issue by benureau** [jdf/processing.py#214]
As there were changes in the internal Mode API, this had to be expected. Nevertheless, Processing 3.2 is out, and many people will default to downloading this version.

**Comment by jdf** [comment]
Thanks for bringing this to my attention.

**Comment by humm** [comment]
It's fixed in 3.2.1: https://raw.githubusercontent.com/processing/processing/master/build/shared/revisions.txt
