### ISSUE TITLE
missing Table API

### ISSUE THREAD

**Issue by aparrish** [jdf/processing.py#215]
I noticed that the Processing Table API is not supported in Processing.py, and judging from [this issue](https://github.com/kazimuth/processing-py-site/pull/50) in the docs repository it looks like this decision was made on purpose. I just wanted to open an issue here to verify that it was an intentional policy decision for Processing.py to not support the Table API. (btw I think this is a reasonable policy decision, since the Table API in Processing is pretty custom-built for Java's type system, and everything the Table API can do Python's standard `csv` module can do better.)

If it is "officially" excluded, I'm going to add it to my list of "things that are different between Processing and Processing.py" to put in a FAQ...

**Comment by aparrish** [comment]
also, if the Table API is in fact excluded, it might be a good idea for consistency sake to remove `loadTable` from the Mode's [list of keywords](https://github.com/jdf/processing.py/blob/b4ad9d60fb2c5be5eab22a506b4b399b3e53ed8c/mode/keywords.txt#L566) and from [core.py](https://github.com/jdf/processing.py/blob/df0e63e8606a865fad39e4a0c6008a0532ad0f64/runtime/src/jycessing/core.py#L328), along with `saveTable`. (Unless it's desirable to continue to support these functions for interoperability with Java Processing or something?)

**Comment by jdf** [comment]
Yes, it is an intentional omission, but not one I feel strongly about. if you think it might be confusing to teachers that they can't simply port a Java example into Python I'd certainly consider exposing those things.

**Comment by aparrish** [comment]
no, I agree that it's a sensible omission—I guess I just wanted it to be "on record" in a searchable place (so that a future overeager contributor doesn't attempt to "restore" the functionality).
