### ISSUE TITLE
DXF, PDF export not working as expected.

### ISSUE THREAD

**Issue by jd-pirtle** [jdf/processing.py#216]
I apologize if this topic has been covered (a quick search points to 'no') but I'm curious about PDF and DXF export...The example PDF export seems to run with no issues (the one with keyPressed), but no PDF is present in the sketch library. Same for DXF...no errors, but no output file.

Should I be providing a path? I'm basing all this on the way those libs behaved in Java mode...so could be user error. :)

**Comment by villares** [comment]
Hey @jd-pirtle , where did you get those examples?
I have ported this https://github.com/arteprog/Processando-Processing/blob/master/exemplos/DXF_SimpleExport.pyde
And it seems to work fine...
