### ISSUE TITLE
NameError: global name 'mouseX' is not defined

### ISSUE THREAD

**Issue by ButterCheezii** [jdf/processing.py#218]
![Error](https://puu.sh/rU2YB/a1af1c4347.png)

I'm developing on macOS Sierra.

**Comment by jdf** [comment]
I'll need some more context. Can you provide a small, complete example that demonstrates this issue?

**Comment by ButterCheezii** [comment]
This seems to happen when calling an event on startup. This can replicate the issue:
```py
def setup():
    size(200, 200)

def mouseMoved():
    bug = mouseX

mouseMoved()
```

**Comment by jdf** [comment]
Ah. Yes, you can't mix static mode and active mode. The correct behavior is for the sketch to refuse to run at all, and to tell you not to do that. :)

I'll fix that.

**Comment by ButterCheezii** [comment]
This should definitely work. It shouldn't error when not mixing.

**Comment by jdf** [comment]
I'm missing something. Could you please provide a complete, minimal example that reproduces the problem but that is also a legal Processing sketch?
