### ISSUE TITLE
global variables are ignored

### ISSUE THREAD

**Issue by ButterCheezii** [jdf/processing.py#219]
Erroneous code:

```py
def setup():
    global bug
    bug = 0

def draw():
    bug += 1
```

Python mode seems to ignore global variables.

![](https://puu.sh/rUyji/4dd20c2218.png)

**Comment by jdf** [comment]
If you want to mutate a global variable, you have to use the `global` keyword in the block where the assignment is made.

```python
def setup():
    global bug
    bug = 0

def draw():
    global bug  # you need this one, too
    bug += 1
```
