### ISSUE TITLE
Can't run Processing.py

### ISSUE THREAD

**Issue by sannychun** [jdf/processing.py#231]
Hello,

I'm new to Processing, so my question may sound quite dumb..but I can't get the Python version to run.
I have downloaded the Python mode from the tab in the upper-right corner of the console. However, I can't get to run even a simple test code such as rect(10,10,10,10). I have attached screenshots of my error messages below.

I am running Processing on a x64 Windows OS. Was wondering if the Windows being in Korean has any effect...

http://imgur.com/a/aalzd

**Comment by jdf** [comment]
Thanks very much for your detailed bug report, which is most helpful.

Yes, there seems to be an issue with folks whose home directories have non-Latin characters. I would love to track this down. If I create a new build, that does some logging, could I trouble you to install it and send me the log it generates?

**Comment by sannychun** [comment]
Thank you for your reply,

Yes I would be glad to help you resolve this issue. I need Processing for my class..I definitely need this working asap.

Kind regards,

Sanny Chun

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jdf** [comment]
Please delete the PythonMode folder from your p3sketches/modes directory, and replace it with the unzipped contents of

   http://py.processing.org/bug/PythonMode.zip

Then try to run a Python sketch, and attach here the contents of the log file created in your temp directory, which will be called

    pythonmode.log.0
