### ISSUE TITLE
Memory leak with PShape

### ISSUE THREAD

**Issue by K2017** [jdf/processing.py#233]
There seems to be an issue regarding the way memory is reclaimed after a sketch is closed in python mode; and it seems it is related to PShapes remaining in memory.

Example Sketch:

```
def setup():
    size(200, 200, OPENGL)
    global MAP
    MAP = ShapeTest()
    MAP.CompileMap()
 
def draw():
    background(0)
    translate(width/2, height/2, 10)
    shape(MAP.Get(), 0, 0)
 
class ShapeTest(object):
    def __init__(self):
        self.Size = 200
 
        self.Map = createShape(GROUP)
 
    def CompileMap(self):
 
        S = 10
 
        for i in range(self.Size):
            for j in range(self.Size):
 
                TileSet = createShape()
                TileSet.beginShape(QUAD)
 
                TileSet.vertex(S + 2*S*i, S + 2*S*j, 0)
                TileSet.vertex(S + 2*S*i, -S + 2*S*j, 0)
                TileSet.vertex(-S + 2*S*i, -S + 2*S*j, 0)
                TileSet.vertex(-S + 2*S*i, S + 2*S*j, 0)
 
                TileSet.endShape()
 
                self.Map.addChild(TileSet)
 
    def Get(self):
        return self.Map
```

Repeatedly running this sketch will eventually cause a 'GC overhead limit' OOME or a 'Java heap space' OOME due to the sketch process remaining active.

**Comment by jdf** [comment]
Very interesting, and I can vaguely guess why it's happening.

If you add

```python
def dispose():
    global MAP
    MAP = None
```

does it mitigate the problem?

**Comment by K2017** [comment]
Sadly it does not. I have tested object (and PShape + PImage) deletion on both stop() and dispose(), but the problem persists.

**Comment by K2017** [comment]
Even simpler case without classes or functions:

```
def setup():
    size(200, 200, OPENGL)
    global Map
    Size = 200
    S = 10
    Map = createShape(GROUP)

    for i in range(Size):
        for j in range(Size):
            
            TileSet = createShape()
            TileSet.beginShape(QUAD)
            
            TileSet.vertex(S + 2*S*i, S + 2*S*j, 0)
            TileSet.vertex(S + 2*S*i, -S + 2*S*j, 0)
            TileSet.vertex(-S + 2*S*i, -S + 2*S*j, 0)
            TileSet.vertex(-S + 2*S*i, S + 2*S*j, 0)
                
            TileSet.endShape()

            Map.addChild(TileSet)
    
def draw():
    background(0)
    translate(width/2, height/2, 10)
    shape(Map, 0, 0)
```

**Comment by jeremydouglass** [comment]
Also some discussion of this on the forum, here: https://forum.processing.org/two/discussion/1202/pshape-memory-leak-garbage-collection-pauses

I'm not sure if it is useful but I wrote a Java version of the original test sketch there which did not exhibit the same problem.

**Comment by jdf** [comment]
Does this happen with a non-`OPENGL` renderer?

**Comment by K2017** [comment]
I can confirm the problem occurs using JAVA2D as well. There seems to be an unrelated issue using FX2D however (A 'connection reset' error on sketch stop), which kills the sketch runner, so I could not test whether the problem occurs with  FX2D.

**Comment by jdf** [comment]
Seems to be fixed. Please reopen if necessary.

**Comment by neilcsmith-net** [comment]
VisualVM suggests this issue still exists as per my comment on the pull request above.
