### ISSUE TITLE
"Reference" folder is missing from Python mode.

### ISSUE THREAD

**Issue by Karim-92** [jdf/processing.py#235]
After installing the Python mode, there should be a folder named "references" downloaded with it to allow the usage of the "Find in reference" functionality in processing. Except that folder isn't downloaded or doesn't exist in the path it should. This renders the "Find in reference" option useless for Python mode and is fixed by copying that folder from the Mode/Java folder into Mode/Python folder.

Shouldn't that folder be bundled in with the Python mode installation?

**Comment by jdf** [comment]
Find in reference now works by opening Python mode web reference.

**Comment by jdf** [comment]
Fixed in 3026.
