### ISSUE TITLE
Python mode should warn for noSmooth/smooth in same sketch

### ISSUE THREAD

**Issue by JonathanMaes** [jdf/processing.py#251]
While asking a question on the processing two forum, we came to the conclusion that I have most probably encountered a bug in python mode.

Here is what the example code looks like, which I put in an empty sketch.

```
background(0)
noStroke()
smooth()
ellipse(30, 48, 36, 36)
noSmooth()
ellipse(70, 48, 36, 36)
```

I tried several different cases:

(1) I tried to put the above mentioned part of code in a new, empty sketch, not enclosed in the setup() function. Result: The ellipses were both drawn smoothly.

(2) I tried to put the above mentioned code in a new, empty sketch, but this time I did put it in the setup() function. Result: The ellipses were both drawn noSmooth-ly.

(3) I tried the same, but now I put the code in the draw() function. Result: The ellipses were both drawn smoothly.

It's most probably a bug; the behavior is pretty inconsistent. When I put it in the setup() function, only then is stuff drawn noSmooth-ly, but everything is drawn that way, it doesn't matter if the smooth() or noSmooth() statements are executed before or after the ellipse()...

And when I put it somewhere else, nothing happens at all.

The full story can be found here: [https://forum.processing.org/two/discussion/21593/image-quality-pixel-image-is-blurry]()

**Comment by jdf** [comment]
An attempt to do what you're doing in Java mode results in ` smooth() and noSmooth() cannot be used in the same sketch`, so Python Mode should detect the same problem and react the same way.
