### ISSUE TITLE
Error in pixel convolution tutorial

### ISSUE THREAD

**Issue by jakobmoss** [jdf/processing.py#258]
### Issue description
There is a small error in the Processing.py pixels tutorial *Sharpen with Convolution*. The main loop is set to be:
```
for x in xrange(xend):
        for y in xrange(yend):
```
which processes the entire image until the position of the mouse, instead of just the rectangle.

### URL(s) of affected page(s)
http://py.processing.org/tutorials/pixels/

### Proposed fix
Change the loop to:
```
for x in xrange(xstart, xend):
        for y in xrange(ystart, yend):
```
This also matches the original example from https://github.com/shiffman/LearningProcessing/blob/master/chp15_images_pixels/example_15_13_Convolution/example_15_13_Convolution.pde

**Comment by jakobmoss** [comment]
This was initially posted at https://github.com/processing/processing-docs/issues/552, but I was told to move it here. 

See also #259 .

**Comment by jdf** [comment]
Hi, Jacob. Thanks for the report.

The Python Mode site is hosted elsewhere, at https://github.com/kazimuth/processing-py-site/issues .

Why not try fixing the mistake and submitting a pull request?

**Comment by AnishHota** [comment]
Could i change the code as suggested by jakob and make a pull request?

**Comment by jdf** [comment]
Yes.
