### ISSUE TITLE
keyPressed does not revert to False when key released

### ISSUE THREAD

**Issue by Apollonius14** [jdf/processing.py#260]
According to the python Processing handbook, if called within a draw() loop, keyPressed should be True only when a key is pressed, then revert to False if no keys are pressed. mousePressed is identical for mouse clicks, and works. keyPressed does not revert to False after the first key. I verified this visually and by checking the value in the prompt.

- System
Windows 10 64 bit

- Code:
```python
def setup():
  size(100,100)

def draw():
  background(255)
  if keyPressed:
     ellipse(50,50,50,50)
```

- Expect to see a circle in the middle of the plot only when a key pressed. Instead I see a circle when the first key is pressed and the circle persists after the key is released.

**Comment by jdf** [comment]
Testing on Linux the code works as expected. I'll try on a windows box when I'm able.

**Comment by villares** [comment]
I have just tested on Processing 3.3.3 on a Windows 10 64bit machine and it worked as expected.

**Comment by Apollonius14** [comment]
Appreciate the checks guys. The problem is definitely real and persisting on my side. Is there any other essential hardware, software or OS information I could provide to help recreate this? Thanks again for the Processing project.

Omar Kadhim


On 13 May 2017, at 00:58, Alexandre B A Villares <notifications@github.com<mailto:notifications@github.com>> wrote:


I have just tested on Processing 3.3.3 on a Windows 10 64bit machine and it worked as expected.

**Comment by jeremydouglass** [comment]
Could be relevant -- Processing has recently had a number of issue reports pop up around Processing 3.3.2 and keyPressed:

https://github.com/processing/processing/issues?utf8=%E2%9C%93&q=is%3Aissues%20keyPressed

**Comment by jdf** [comment]
https://github.com/processing/processing/issues/5049

May be relevant. Had you held down the first key at all?

**Comment by Apollonius14** [comment]
This may well be it. I'll update to 3.3.3 ASAP and let you know.

Omar Kadhim


On 14 May 2017, at 20:38, Jeremy Douglass <notifications@github.com<mailto:notifications@github.com>> wrote:


Could be relevant -- Processing has recently had a number of issue reports pop up around Processing 3.3.2 and keyPressed:

https://github.com/processing/processing/issues?utf8=%E2%9C%93&q=is%3Aissues%20keyPressed

**Comment by Apollonius14** [comment]
Jon thanks for your reply. I believe it's a bug that was fixed in 3.3.3 and I'm using and older version. If the issue persists after that I'll let you know.

Omar Kadhim


On 14 May 2017, at 21:44, Jonathan Feinberg <notifications@github.com<mailto:notifications@github.com>> wrote:


processing/processing#5049<https://github.com/processing/processing/issues/5049>

May be relevant. Had you held down the first key at all?

**Comment by Apollonius14** [comment]
Downloaded 3.3.3. keyPressed now reverts to False when a key is released *only if* the key is quickly pressed and not held. I think a fix for this second issue has been included in the next release https://github.com/processing/processing/issues/5049.

**Comment by jdf** [comment]
Closing for seemingly being Processing's bug. Please reopen if necessary.
