### ISSUE TITLE
Are the processing.py website reference files in a public repo?

### ISSUE THREAD

**Issue by jeremydouglass** [jdf/processing.py#261]
Is the reference documentation on the website:

http://py.processing.org/reference/

...available somewhere, in this or a related github repo? 

I couldn't find it in a quick check of:

-  https://github.com/jdf/processing.py
-  https://github.com/jdf/processing.py.web
-  https://github.com/processing/processing-docs

The GSOC project for a new [Processing.R](https://github.com/gaocegege/Processing.R) mode will need its own reference examples sketches, and it might model some of its public documentation after Processing.py. I'm wondering how that information is structured / generated / stored for modes.

**Comment by jdf** [comment]
You want

https://github.com/kazimuth/processing-py-site

**Comment by jeremydouglass** [comment]
Thank you so much, @jdf. The Processing.py mode is a great model for Processing.R, so @gaocegege will be looking at all this wonderful work for best practices and inspiration during the GSOC period this summer.
