### ISSUE TITLE
unittest gives error

### ISSUE THREAD

**Issue by marco-piccolino** [jdf/processing.py#264]
Hi there, and thanks for a great tool.

I was trying to use unittest (which is part of the PSL) with the following program:

```python
import unittest
    
def sort_i(unsortedArray,direction="ASC"):
    sortedArray = [];
    for i in unsortedArray[1:]:
        print i
    return sortedArray

class TestSortInsertion(unittest.TestCase):

    def test_base(self):
        self.assertEqual(sort_i([1,3,4,2]), [1,2,3,4])

if __name__ == '__main__':
    unittest.main()
```
But I get the following error:

```
Fprocessing.app.SketchException: AttributeError: FakeStdErr instance has no attribute 'flush'
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:240)
	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:227)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:122)
	at java.lang.Thread.run(Thread.java:748)
```
Any idea?

thanks a lot

**Comment by jdf** [comment]
Fixed in 3023, which is uploading now.

**Comment by marco-piccolino** [comment]
Thank you! :-)

Il 08 lug 2017 2:21 PM, "Jonathan Feinberg" <notifications@github.com> ha
scritto:

**Comment by jdf** [comment]
Prego. :)

**Comment by jeremydouglass** [comment]
With this issue closed, should the example code above run correctly? Even with the simplest uses of unittest using the __main__ method, like this:

import unittest

```
class TestSame(unittest.TestCase):
    def test_base(self):
        self.assertEqual([1,2,3,4], [1,2,3,4])

if __name__ == '__main__':
    unittest.main()
```

... I'm seeing this error:

> processing.app.SketchException: SystemExit: False  
> 	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:240)  
> 	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:122)  
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by jdf** [comment]
No, this is a an unrelated and weird bug.

**Comment by jdf** [comment]
Hmm, actually the test passes (that's what gives `OK` in the output), but unittest appears to be raising SystemExit.

**Comment by jdf** [comment]
I think I'll catch SystemExit and turn it into PAPPlet.exit().

**Comment by jdf** [comment]
Addressed in build 3034, or you can also do

```python
if __name__ == '__main__':
    unittest.main(exit=False)
```

as a workaround meanwhile.

**Comment by jdf** [comment]
You're welcome! Maybe the [forum](https://forum.processing.org/two/categories/python) users would like to hear about it?

**Comment by jeremydouglass** [comment]
Good suggestion -- I bundled it into a collection repo called [processingpy_import_examples](https://github.com/jeremydouglass/processingpy_import_examples) and linked to it [on the forum](https://forum.processing.org/two/discussion/comment/111014/#Comment_111014).
