### ISSUE TITLE
Python 3 Compatibility?

### ISSUE THREAD

**Issue by Enteleform** [jdf/processing.py#269]
Is there any chance of making this wrapper compatible with Python 3?  
What would be required of contributors to make this happen?

**Comment by jdf** [comment]
The Jython project would have to create a Python 3 implementation.

**Comment by jeremydouglass** [comment]
For reference an incomplete Jython3 prototype exists, but is in "very early stages" -- it is not clear if it is coming in the next few years, if ever.

https://github.com/jython/jython3
