### ISSUE TITLE
Add site-packages

### ISSUE THREAD

**Issue by jdf** [jdf/processing.py#279]
Add a new site-packages directory under Documents/Processing/libraries where users can keep libraries available to all of their sketches.

**Comment by jdf** [comment]
Per @awmartin.

**Comment by jdf** [comment]
Available in build 3027.

**Comment by awmartin** [comment]
This is amazing. It will effectively enable Python developers to contribute libraries to Processing now. Thanks so much!

**Comment by awmartin** [comment]
@jdf How long does it usually take for a new build to make its way to the Contribution Manager?

**Comment by jdf** [comment]
I don't know. That's a good question for someone in @benfry's processing family.

**Comment by jeremydouglass** [comment]
I'm really enjoying this feature.

A note for future users: import "does the right thing" with overriding site packages. If you add `foo.py` to `/site-packages` and `foo.py` to your sketch folder, then `import foo` will correctly import from the sketch folder, not site-packages.
