### ISSUE TITLE
Is Processing's `thread()` implemented on Python Mode?

### ISSUE THREAD

**Issue by villares** [jdf/processing.py#281]
I have set a minimal example... that should print "hi" continously, but `thread()` is undefined.
(Perhaps`PApplet.thread(self, "my_thread")` should work?)
```
def setup():
    size(100, 100)
    thread("my_thread")
    
def draw():
    pass
    
def my_thread():
    println("hi")
```

**Comment by jdf** [comment]
I wasn't aware of that feature. Let me look into it.

**Comment by jdf** [comment]
Pushed in build 3033.
