### ISSUE TITLE
Incorrectly removing final linebreak on sketch re-open

### ISSUE THREAD

**Issue by jeremydouglass** [jdf/processing.py#285]
Opening a Processing.py sketch in PDE loads the text with the final linebreak missing. Saving any tab then introduces an additional change that strips away the final line break on that tab.

This is a minor issue, but an annoyance because part of the unix standard is a [linebreak at the end of the final line](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file) -- multiple checkers and source control tools add warnings or complain if that linebreak isn't there, and because Processing.py constantly re-introduces the error after every edit, it is easy to accidentally propagate the error back into e.g. version control again and again.

**Comment by jdf** [comment]
This appears to be a bug in Processing itself, not in Python Mode--I was able to reproduce it in the Java mode editor, which Python Mode's editor extends. You might consider filing the bug at processing/processing.

**Comment by jeremydouglass** [comment]
Good point -- should have checked that first....

**Comment by jeremydouglass** [comment]
Ok, filed: processing/processing#5327
