### ISSUE TITLE
Problem with processing with some examples

### ISSUE THREAD

**Issue by Hextejas** [jdf/processing.py#288]
The error I get goes something like this:
Cannot compile vertex shader:0:1 error: syntax error unexpcted EOL, expecting INTCONSTANT.

Other examples work ok. I just installed processing for evaluation and was trying what looked like some complicated graphics program's it's quite possible that I am missing a library somewhere.
I am running on Sligo l8nux.

Thanks

**Comment by jdf** [comment]
I can't guess what isn't working.

**Comment by Hextejas** [comment]
Huh, there are at least 5 examples that won't compile. Did you want the name of one ?

**Comment by jdf** [comment]
Yes.
