### ISSUE TITLE
"with" statements not supported in PGraphics objects

### ISSUE THREAD

**Issue by haschdl** [jdf/processing.py#296]
hello @jdf and other contributors!

One of the very useful features of using the Python mode is to be able to write the `with` statements, as exemplified in `Python Mode Differences -> WithStatements`:

>[...] instead of
> 
>     pushMatrix()
>     translate(10, 10)
>     rotate(PI/3)
>     rect(0, 0, 10, 10)
>     popMatrix()
>     rect(0, 0, 10, 10)
> 
> you can write
> 
>     with pushMatrix():
>         translate(10, 10)
>         rotate(PI/3)
>         rect(0, 0, 10, 10)
>     rect(0, 0, 10, 10)
 
The problem however is that `with` statements throw an exception if used on an instance of `PGraphics`. Example:
```Java
buffer = createGraphics(500,500)
buffer.beginDraw()
buffer.fill(0x00FF0000)
buffer.ellipse(10, 10, 10, 10)
with buffer.pushMatrix():
    buffer.translate(10, 10)
    buffer.ellipse(10, 10, 10, 10)

image(buffer,0,0)
```

This is the error:

> processing.app.SketchException: AttributeError: 'NoneType' object has no attribute '__exit__'
> 	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:240)
> 	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
> 	at java.lang.Thread.run(Thread.java:748)

Is that a known issue? Under a quick assessment, do you see it as a big task to make `with` statements work with PGraphics?

**Comment by jdf** [comment]
It's difficult, not impossible, and reasonable to ask for. Indeed, I believe it may already have been requested. :)

The next time I have a good 5 hour block of time, I'll give it a shot.

**Comment by jdf** [comment]
Pushed in build 3039.

**Comment by haschdl** [comment]
thank you @jdf , I appreciate it!  I confirm this example works now:
```Java
buffer = createGraphics(250,180)
with buffer.beginDraw():
    buffer.fill(0x00FF0000)
    buffer.ellipse(10, 10, 10, 10)
    with buffer.pushMatrix():
        buffer.translate(10, 10)
        buffer.ellipse(10, 10, 10, 10)
````

**Comment by jdf** [comment]
You're welcome!
