### ISSUE TITLE
Cannot install Python Mode in current Processing (Windows)

### ISSUE THREAD

**Issue by mgmalheiros** [jdf/processing.py#298]
As of the last few days, I cannot install Python Mode in Processing 3.3.7 (Windows).

Every time I go to the screen for installing modes and select Python Mode (3040), the download starts and then end immediately with the following message:

  Could not find a mode in the downloaded file.

Perhaps it is a server-side problem, but by taking a look on the Processing sources I could not find the expected server URL to test it out.

Other modes, like the p5.js or the REPL install and run fine. I´ve tested in two distinct Windows machines within different networks.

Does anyone have the same problem?

**Comment by AluminiumTech** [comment]
Yup. Can confirm have the exact same issue.

**Comment by jdf** [comment]
Known issue with Procesing: https://github.com/processing/processing/issues/5554

**Comment by yashaslokesh** [comment]
Thanks @raj-raghuwanshi, this solution worked for me on macOS Sierra

**Comment by mgmalheiros** [comment]
Thank you all for the support!

I had success doing the manual installation both for Windows and Linux. The correct paths are described in #299.

As this is an issue for Processing IDE itself, I will close this ticket,
