### ISSUE TITLE
Can't install Python mode for Processing (Mac OS)

### ISSUE THREAD

**Issue by raj-raghuwanshi** [jdf/processing.py#299]
Whenever I attempt to download the mode, it gives me this error:

"Could not find a mode in the downloaded file"

Here is a screenshot: https://imgur.com/a/hFwg9mO

Is there any way to solve this issue? If not, is it possible to manually download the mode and move it into the Processing mode folder?

Edit: I am using 3.3.7 Processing, but even when I change versions, it still doesn't work.

**Comment by jdf** [comment]
Known issue in Processing: https://github.com/processing/processing/issues/5554

**Comment by raj-raghuwanshi** [comment]
@jdf Are there any workarounds, or is waiting the only current option?

**Comment by villares** [comment]
Please try downloading the mode from: https://py.processing.org/3/PythonMode.zip

**Comment by raj-raghuwanshi** [comment]
@villares I downloaded it, but where should I move the folder to? I'm new to Processing, so forgive my lack of knowledge.

**Comment by villares** [comment]
Hi, 
It's not in the app contents! it's under you macOS user:
Documents > Processing > modes > PythonMode (this is the uncompressed downloaded folder)

**Comment by raj-raghuwanshi** [comment]
@villares It worked! Thanks so much!

**Comment by aysual** [comment]
i have the same problem.
in windows 10, processing 3.5.4, phyton 3063
and i cant run even the simple codes.
i tired to avoid firewall to block processing and also the solution written up, downloading the phton mode manually and copying to modes file. but still there is no action when i press play.
what do i do?

**Comment by tabreturn** [comment]
I've just tested a fresh install of Python mode on my Windows machine; it works fine. Can you switch to Python mode okay?

![intro-to-processing-switch-to-python-mode](https://user-images.githubusercontent.com/9858145/98457095-092d6a80-21e9-11eb-977e-8f7a7b036398.png)

Does the Processing console display any errors?
