### ISSUE TITLE
line() causes TypeError (Linux)

### ISSUE THREAD

**Issue by azapletal** [jdf/processing.py#305]
Drawing a simple line (just fixed coordinates as given in examples) causes the error below. Other drawing methods (e.g. point, ellipse, quad) work fine. 
Linux 64bit (FC27), Processing 3.4

```
processing.app.SketchException: TypeError: 'unicode' object is not callable
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:240)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jdf** [comment]
This program works fine for me:

```python
line(10, 10, 30, 30)
```

Please provide a minimal, complete example program that reproduces the problem.

**Comment by azapletal** [comment]
Thx a lot for your quick reply, of course the simple example works for me as well.
My fault: I do some CSV-type file pre-processing to get some data and unfortunately used a variable named 'line' for iteration. Similar to the loadStrings() example.  Moved this into setup() and everything is fine. Sorry once more, I really oversaw this.
