### ISSUE TITLE
ImportError: No module named ast

### ISSUE THREAD

**Issue by CarlsenSmart** [jdf/processing.py#309]
I am on a windows 10 and downloaded the python mode.

I get the following error message when I tried to run:

```
processing.app.SketchException: ImportError: No module named ast
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:240)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

I have python 2.7.3 installed, but also others.
Do you have any idea why this error occurs ? 
\- It looks like ast is a standard module in python, so it is a bit weird.

I have also noticed that you only tested python mode on Mac and Ubuntu.

Is there anything I can do to help you ? - I don't what but maybe you could guide me :)

**Comment by CarlsenSmart** [comment]
rect(0,0,100,100) doesn't work, but either does your example :) 
- It's still the same error.

**Comment by jdf** [comment]
Python Mode does not use your system python; it's self-contained. Are you using Python Mode, in the Processing IDE, or are you trying to run a sketch as standalone using the jar file?

**Comment by jdf** [comment]
I can't even imagine what could cause such an error.

**Comment by CarlsenSmart** [comment]
Is there a way to uninstall Processing ? 

I tried to download Processing again a place it in a different folder, but it seems to remember the previous modes, so I assume that there are some settings files located somewhere. I could try to delete them and try install Pythen Mode again :)

or maybe you can tell me where the Python Interpreter's modules are installed so I could add the missing module ? :)

**Comment by jdf** [comment]
The modules are integral to the mode, in a jar file. You can't install any.

The modes are in your Processing user directory, which is also where all of your saved sketches go. I believe that's HOME/Documents/Processing

**Comment by CarlsenSmart** [comment]
My computer is a work computer and we have several folders synced to our users. Maybe it is the path the messes things up.

I can see that the files are installed within the following path:
`\\dc01.bp.local\users$\thc\Documents`

So maybe it should be saved on the local user's Documents folder ?
like the following:
`C:\Users\thc\Documents`

**Comment by jdf** [comment]
I would expect a network-mounted drive to cause problems, yes. If you can set your home directory to a local directory, I bet that will work.

**Comment by CarlsenSmart** [comment]
It seems like that the 'home' directory is set by the 'ProfileImagePath' on Windows. And my is actually set to the local `C:\Users\thc` path. So I think it is better to have Processing install it's files depending on that variable. 
But nevertheless, I think we did find out what the problem was and I'm going to close this issue :)
\- Thanks for the help :)

**Comment by CarlsenSmart** [comment]
I don't know how you would get the info in Java, but here is a way to get it in Python:

```
import winreg
import os


user_info = os.popen('whoami /user /fo list').read()

SID = user_info[user_info.index("SID:")+4:].strip()

key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, r'SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\\' + SID)


print(winreg.QueryValueEx(key, "ProfileImagePath")[0])
```
