### ISSUE TITLE
PVector.random2D return 'processing.core.PVector'

### ISSUE THREAD

**Issue by etberzin** [jdf/processing.py#317]
which messes as type(PVector(12, 13)) is <type '__main__.PVector'>

**Comment by jdf** [comment]
Can you give me a complete, minimal example of a program that doesn't work because of this distinction?

**Comment by etberzin** [comment]
emmm… for a little convenience, I use a function to convert tuple to PVector and replace the ` __add__ `function, let PVector and tuple can be added, code below
```python
def _new_vector_add_(self, rhs):
    if isinstance(rhs, PVector) :
        return PVector._old_add_(self, rhs)
    if isinstance(rhs, tuple) :
        return self + tuple2v(rhs)
    raise TypeError('rhs must be a PVector or a tuple')


def tuple2v(*tuples):
    ret = []
    for i in tuples:
        if(isinstance(i, PVector)):
            ret.append(i)
        elif len(i) == 2:
            x, y = i
            ret.append(PVector(x, y))
        elif len(i) == 3:
            x, y, z = i
            ret.append(PVector(x, y, z))
        else:
            raise TypeError('only accept tuple:2 or tuple:3.')
    return ret[0] if len(ret) == 1 else tuple(ret)

```

of course I have made a workaround by adding an additional if case.
@jdf

**Comment by jdf** [comment]
Addressed in https://github.com/jdf/processing.py/commit/5e1356f74acb9ff751eaf82e1ed01c96abf167f3, and will be released soon.

**Comment by jdf** [comment]
Deployed to build 3048.
