### ISSUE TITLE
<PGraphics>.ellipse() encountered TypeError at 3048

### ISSUE THREAD

**Issue by marshfolx** [jdf/processing.py#326]
Message : **processing.app.SketchException: TypeError: 'java.awt.geom.Ellipse2D$Float' object is not callable**

code like this:
```python
size(100, 100)
pg = createGraphics(40, 40)

pg.beginDraw()
pg.background(100)
pg.stroke(255)
pg.ellipse(20, 20, 10, 10)
pg.endDraw()
image(pg, 9, 30)
image(pg, 51, 30)
```
while `pg.line()` works well.
In addition, I downloaded the package directly from `https://py.processing.org/3/PythonMode.zip` because of some touble with PDE builtin downloader, is this the cause?

**Comment by jdf** [comment]
Ugh. PGraphicsJava2D has an `ellipse` field that's shadowing the function. I will try to work around it.

**Comment by jdf** [comment]
As a workaround, you can do

```python
size(100, 100, P2D)
pg = createGraphics(40, 40, P2D)
```

and your program will work as expected.

Thanks for reporting this!

**Comment by jdf** [comment]
This fix is in build 3049 and later.
