### ISSUE TITLE
Support new methods circle, square, push and pop

### ISSUE THREAD

**Issue by berinhard** [jdf/processing.py#336]
Processing 3.5.3 added [4 new methods](https://github.com/processing/processing/blob/master/build/shared/revisions.txt#L31) to its API: `circle`, `square`, `push` and `pop` and they aren't available in the current version of processing.py.

I was looking at the code and I don't know if I'm being naive, but it seemed to me that it's just a matter of adding those methods [to this line](https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/core.py#L260), since none of the new method are Python reserved words.

@jdf is this approach reasonable? I fell like there's also some Java code to be added somewhere, but I'm not that familiar with Jython. Let me know if and how I can help with that. Thanks!

**Comment by jdf** [comment]
Unless any of those function names collide with Processing variables or Python keywords, then you're exactly right; you just have to add those new names to that string. Give it a try. :)
