### ISSUE TITLE
Just asking

### ISSUE THREAD

**Issue by Someone1002** [jdf/processing.py#342]
is support for things like matplotlib and numpy planned in the python version? I'm asking because I can't seem to get the actual python to work.

**Comment by villares** [comment]
This project is based on Jython (a Python 2 implementation that runs on JVM) so matplotlib or numpy will probably never be compatible. You can use "pure Python 2" libraries and a rich ecosystem of Java libraries, many available through the Processing IDE. 

Please take the time to investigate what Processing.org (and py.processing.org) is about and enjoy!

**Comment by Someone1002** [comment]
ok thanks
