### ISSUE TITLE
Exported application fails to obey "Full Screen (present mode)" setting.

### ISSUE THREAD

**Issue by villares** [jdf/processing.py#356]
On Mac OS, Processing 3.5.4, Processing Mode 3056, exporting an application with
"Full Screen (present mode)" checkbox at the export panel does not generate an application that fills the whole screen as in Java Mode.

To reproduce, create a simple sketch and use File > Export Application... then choose the mentioned checkbox.

```python
def setup():
    size(800, 600)

def draw():
    fill(random(256), random(256), random(256))
    circle(mouseX, mouseY, 50)
```

Might be related to Processing failing to remove the OS menu when unsing `fullScreen()` + present command:
https://github.com/jdf/processing.py/issues/354

**Comment by mpsftw** [comment]
This only works differently when using size() and the Full Screen checkbox. It works as expected with using fullScreen() with the Full Screen checkbox.

**Comment by villares** [comment]
I see... but for me both the "present" and "full screen lon export" features have as main use to 'frame' a smaller (non-fullscreen) sketch in a neutral background for public presentation.

**Comment by mpsftw** [comment]
I understand, I just wanted to clarify for future reference.

**Comment by villares** [comment]
It would be nice if we could test if this has any impact in this `sketchPath()` issue:
https://discourse.processing.org/t/using-save-and-exporting-application-macos/19549/11
