### ISSUE TITLE
Fake Module for IDE Code Completion

### ISSUE THREAD

**Issue by mlg556** [jdf/processing.py#365]
This is a request: I would like to be able to write `python3` code using any IDE I want, but also get the benefits of code completion. However, since `processing.py` is not a package, this is not currently possible. What I am requesting is something like [fake-bpy-module](https://github.com/nutti/fake-bpy-module) where we have a fake module which can be imported using any IDE so that code completion works. The code then will obviously be run by `java -jar processing-py.jar something.py`.

**Comment by jeremydouglass** [comment]
> I would like to be able to write `python3` code using any IDE I want, but also get the benefits of code completion. However, since `processing.py` is not a package, this is not currently possible.

Processing.py is Python 2 running on Jython (JVM). You won't ever be able to run python3 code with it.

For python3 in any IDE check out:

https://github.com/p5py/p5.
