### ISSUE TITLE
Python Mode in Processing not working

### ISSUE THREAD

**Issue by pixel1973** [jdf/processing.py#369]
Hi

I am new to coding.

The Python Mode in Processing does not seem to work properly. There is no output when I try print ("Hello world").

My installation:
Windows 10
Python 3.8 (32bit)
Processing 3.5.4
Python Mode 3058

I already tried to switch of all Firewall and Antivirus software and also started Processing as Administrator. None of them helped.

Thank you very much in advance for your help.

Regards,
pixel1973

**Comment by ComedyRelief** [comment]
Bump. Same issue. Downloaded this morning.
Win10 1809
Processing 3.5.4
Python 3058
Python 3.8 installed (going to install 2.x to see if that changes anything)

Java code runs fine. If I switch to py mode then the run button blits to green for a second on click and then goes back to grey. Nothing happens and the code isn't executed.

**Comment by jdf** [comment]
Sorry, folks. Build 3059 is going up now. I had built the mode with a more recent version of Java, which Processing doesn't support.

**Comment by ComedyRelief** [comment]
Awesome! Thank you for the quick fix. First impressions have some skeleton code working flawlessly. Thank you!

**Comment by pixel1973** [comment]
Thank you very much for the quick fix.
