### ISSUE TITLE
Python Mode does nothing when clicking run

### ISSUE THREAD

**Issue by bytezen** [jdf/processing.py#374]
Hi All-
I am experimenting with using Python for a class that I am teaching (switching from Java Processing). I have installed Python Mode 3061 in Processing 3.5.4 on a MacBook Pro running 10.14.6. I have also tried Python Mode using Processing 3.4 with no success.  For example, when I run the examples OR a basic sketch like:

def setup():
   size(300,300)

def draw():
    background(100,0,0)

Nothing happens. I am also unable to get anything to print to the console if I add a print statement. 
Does anyone have any leads on how I can troubleshoot the problem? I have searched the forums, but I have not found a relevant solution.

I am unfamiliar with how Jython and Processing are integrated, but if someone can give me some suggestions on things to investigate then I would be happy to do the leg work and report my results.

Interestingly, I can not get the sketch to generate an error either. The following generates no output to the console nor changes the editor:

def setup():
   size(300,300)
   println("this is a test")
afdsfds

def draw():
    background(100,0,0)

**Comment by jdf** [comment]
Bah; I'm sorry. This happens when I use an up-to-date Java to build a release, instead of the required ancient version. I've pushed a new build. Please uninstall PythonMode, restart Processing, and install Python Mode again. You should get 3062.

**Comment by bytezen** [comment]
Out of curiosity is this because you are using JDK 11 (or whatever the latest is?) Because I 99.9% use Java with Processing I am totally out of the Java Universe these days. I recently downloaded the (I think) latest JDK to start to learn the new language features. I am trying to understand how all of this fits together better, which is why I ask.

Cheers.

**Comment by bytezen** [comment]
Sweet! It works. FYI the build that was downloaded was 3059 not 3062.
