### ISSUE TITLE
Cannot start python sketch runner on Arch Linux

### ISSUE THREAD

**Issue by MLK97** [jdf/processing.py#379]
I repeatedly tried over the recent months to get Processing.py running on my Arch Linux laptop. 
I downloaded and unpacked the PythonMode inside the sketchbook/modes folder since I can't download, install or update the Python mode via the processing UI, as it gives me a downloading error.
Anyways when clicking on the available modes the Python mode is listed, however clicking on it shuts down the program and prints the error message "Cannot start python sketch runner".
My java -version output is:
```bash
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
```
Closing the error window yields the following output on console
```bash
java.io.IOException: Cannot run program "/usr/lib/jvm/java-8-openjdk/bin/java": error=2, No such file or directory
[...]
/home/maximilian/sketchbook/modes/PythonMode/formatter/pep8.py:100: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
```
I downloaded processing via AUR and the version there was last updated on 2020-06-07.
Thanks in advance for any help or comment.

**Comment by jdf** [comment]
OpenJDK is not supported by Processing.

https://github.com/processing/processing/wiki/Supported-Platforms#linux
.
-- 
-- 
Jonathan Feinberg jdf@pobox.com http://MrFeinberg.com

**Comment by MLK97** [comment]
Thank you for clarifying. I now changed to Oracles JDK8, however I am still running into the same error.

**Comment by MLK97** [comment]
There seems to be a conflict on the package site. 
For anyone who has the same problem downloading the processing-jdk8 AUR instead of the processing AUR package resolved the issue.
