### ISSUE TITLE
Processing 4 bug: no UnboundLocalError's

### ISSUE THREAD

**Issue by tabreturn** [jdf/processing.py#390]
In Processing 3, the editor (correctly) displays unbound local errors errors. In Processing 4, the sketch 'runs' but doesn't actually work properly.

![Screenshot from 2021-08-13 09-07-03](https://user-images.githubusercontent.com/9858145/129270358-c2b3d112-008c-4139-ba9e-29adaffe1b33.png)

I'm using this build of Processing.py: https://github.com/tabreturn/processing.py-for-processing-4

**Comment by benfry** [comment]
Do any errors/warnings make it through, or is it just `UnboundLocalError`s that have trouble?

**Comment by tabreturn** [comment]
Doh! Turns out it's all errors/warnings that won't appear. 

Note that I ran 4.0b1 again to test this. The 4.0b1 processing.py build wouldn't run on 4.0b3 (some java.lang.NullPointerException). I tried to build processing.py again using the 4.0b3 source but couldn't build successfully (likely due to my lack of Java knowledge).

**Comment by benfry** [comment]
Ok, though if it's all errors, that's probably easier to fix. 

If you can file something for the NPE I can look into it—there shouldn't be anything in beta 3 that would break Python Mode, unless it's a Java 17 issue.

**Comment by tabreturn** [comment]
Reported issue in Processing 4: https://github.com/processing/processing4/issues/350
