### ISSUE TITLE
No python mode on processing 4.0b1

### ISSUE THREAD

**Issue by kevinpacayra** [jdf/processing.py#392]
[https://imgur.com/cRQ98zI](url)

Please check the image and what's the guide to fix this I'm using Windows 64 bit. Thank you in advance.

**Comment by tabreturn** [comment]
Right now, Python Mode doesn't support Processing 4. Use Processing 3.5.4 instead.

**Comment by kevinpacayra** [comment]
> Right now, Python Mode doesn't support Processing 4. Use Processing 3.5.4 instead.

Downloaded and got the same issue as the image above that I sent. What could be the reason for this to happen?

**Comment by tabreturn** [comment]
I see. Thanks, I've reported the issue. Hopefully it's resolved soon. 

In the mean time, you can download the files here --
https://raw.githubusercontent.com/tabreturn/processing.py-for-processing-4/main/PythonMode-for-Processing3.zip

In your _Documents_ folder on Windows, there should be a folder named _Processing_; inside that is another folder named _modes_. Copy the _PythonMode_ folder (from the download above) into _modes_.

**Comment by kevinpacayra** [comment]
> I see. Thanks, I've reported the issue. Hopefully it's resolved soon.
> 
> In the mean time, you can download the files here --
> https://raw.githubusercontent.com/tabreturn/processing.py-for-processing-4/main/PythonMode-for-Processing3.zip
> 
> In your _Documents_ folder on Windows, there should be a folder named _Processing_; inside that is another folder named _modes_. Copy the _PythonMode_ folder (from the download above) into _modes_.

**Comment by kevinpacayra** [comment]
> > I see. Thanks, I've reported the issue. Hopefully it's resolved soon.
> > In the mean time, you can download the files here --
> > https://raw.githubusercontent.com/tabreturn/processing.py-for-processing-4/main/PythonMode-for-Processing3.zip
> > In your _Documents_ folder on Windows, there should be a folder named _Processing_; inside that is another folder named _modes_. Copy the _PythonMode_ folder (from the download above) into _modes_.

This was I'm waiting as I've read past issues I probably just downloaded the wrong PythonMode file. Thanks a lot @tabreturn

**Comment by kevinpacayra** [comment]
I moved the downloaded file on _This PC > Documents > Processing > modes_ folder but there was another _modes_ folder inside and I move it there and that works. Probably by deleting that another _modes_ file it will still work but I think I will leave it as it is. Thanks for the guide @tabreturn. Closing this issue now.
